# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-AngelXML-Auth
version:      0.14
version_from: lib/WebService/AngelXML/Auth.pm
installdirs:  site
requires:
    CGI:                           0
    strict:                        0
    Test::More:                    0
    Test::XML:                     0
    XML::Writer:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
